# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/NIXOS_SYS";
      fsType = "ext4";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/897d746b-9752-4639-9598-cea5cdb2bf75";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/sdb1";
      fsType = "vfat";
    };

  fileSystems."/opt/chiaplot" = {
    device = "/dev/disk/by-uuid/728dfd8a-2f8f-4322-9d52-b19ade850f1c";
    fsType = "ext4";
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/fcaaa04d-0c2e-469b-9755-eea13aaeb2cd"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
