{config, pkgs, lib, ... }:

let
  registry = (import ../../../data/service-registry.nix).karakeep;
  meili = (import ../../../data/service-registry.nix).meilisearch;

in {
  config = {
    services.meilisearch = {
      enable = true;
      # Explicitly set the meilisearch version, because the service
      # default is an older version if the stateVersion is older than
      # 25.05. I have already manually done the migration so nothing
      # to worry about.
      package = pkgs.meilisearch;
      listenPort = meili.port;
      listenAddress = "127.0.0.1";
      settings = {
        experimental_dumpless_upgrade = true;
      };
    };
    
    # karakeep 0.32.0 builds with pnpm_9 (9.15.9), which nixpkgs marks
    # insecure. Overriding karakeep to pnpm_10/11 does not work: the released
    # tag's pnpm-lock.yaml was generated by pnpm 9, so the --frozen-lockfile
    # install in fetchPnpmDeps fails with ERR_PNPM_LOCKFILE_CONFIG_MISMATCH on
    # patchedDependencies. Upstream karakeep main is on pnpm 11 but has not cut
    # a release since 2026-05-08 -- see NixOS/nixpkgs#529285 (pnpm 9 EOL
    # tracking, where karakeep is one of the last two holdouts) and #539235.
    # pnpm only runs inside the build sandbox against a fixed-output pnpmDeps,
    # so the CVEs are not reachable at runtime. Drop once karakeep releases.
    vital.insecurePackages = [ "pnpm-9.15.9" ];

    services.karakeep = {
      enable = true;
      meilisearch.enable = true;
      browser.enable = true;
      browser.port = registry.ports.browser;
      extraEnvironment = {
        PORT = "${toString registry.ports.ui}";
        DISABLE_SIGNUPS = "true";
        DISABLE_NEW_RELEASE_CHECK = "true";
        OPENAI_API_KEY = "ollama";
        OPENAI_BASE_URL = "http://localhost:${toString config.services.ollama.port}/v1";
        INFERENCE_TEXT_MODEL = "gemma4:e4b";
        INFERENCE_IMAGE_MODEL = "gemma4:e4b";
        INFERENCE_CONTEXT_LENGTH = "50000";
      };
    };

    services.nginx.virtualHosts."${registry.domain}" = {
      enableACME = true;
      forceSSL = true;
      locations."/".proxyPass = "http://localhost:${toString registry.ports.ui}";
    };
  };
}
