# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c71cbcab-4e28-4dbe-bd1e-308f9d22f6b0";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4BE4-0BC3";
      fsType = "vfat";
    };

  fileSystems."/var/lib/chia/plotting/nvme1" =
    { device = "/dev/disk/by-label/CHIAPLOT1";
      fsType = "ext4";
    };

  fileSystems."/var/lib/chia/plotting/nvme2" =
    { device = "/dev/disk/by-label/CHIAPLOT2";
      fsType = "ext4";
    };

  fileSystems."/var/lib/chia/farm/1" =
    { device = "/dev/disk/by-label/CHIAFARM1";
      fsType = "ext4";
    };

  fileSystems."/var/lib/chia/farm/2" =
    { device = "/dev/disk/by-label/CHIAFARM2";
      fsType = "ext4";
    };

  fileSystems."/var/lib/chia/farm/3" =
    { device = "/dev/disk/by-label/CHIAFARM3";
      fsType = "ext4";
    };

  fileSystems."/var/lib/chia/farm/4" =
    { device = "/dev/disk/by-label/CHIAFARM4";
      fsType = "ext4";
    };

  fileSystems."/var/lib/chia/farm/5" =
    { device = "/dev/disk/by-label/CHIAFARM4";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2ca4fc6a-7643-4a77-af7f-14a57011ab23"; }
    ];

  nix.maxJobs = lib.mkDefault 16;
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}
