[tool.poetry]
name = "medea-clipper"
version = "1.0.0"
description = "Cross machine web app for clip boarding"
authors = ["Break Yang <breakds@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
bottle = "^0.12.23"

[tool.poetry.dev-dependencies]
paperclip = "^1.8.*"
click = "^8.1.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
