# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "mpt3sas" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "zfs" ];
  boot.zfs.extraPools = [ "VAULT_ROOT" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f6521164-d262-40a5-b056-5b9060a48e7c";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F05C-BF44";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # The ZFS Array has 15 disks = 3 rows x 5 per row. S/N are shown below.
  #
  # +--------------------+   +--------------------+   +--------------------+
  # |      5PHA9DYD      |   |      5PJ2MNYD      |   |     5PHZPEGD       |
  # +--------------------+   +--------------------+   +--------------------+
  # |      5PJ1B6GD      |   |      5PJ24HRD      |   |     5PHAGDZD       |
  # +--------------------+   +--------------------+   +--------------------+
  # |      5PHWZXJD      |   |      5PJ2G9ZD      |   |     5PJ2KJVD       |
  # +--------------------+   +--------------------+   +--------------------+
  # |      5PHWM6LF      |   |      5PJ1NM3D      |   |     5PHDEM8D       |
  # +--------------------+   +--------------------+   +--------------------+
  # |      5PHXP4BD      |   |      5PJ2MADD      |   |     5PHYKU7D       |
  # +--------------------+   +--------------------+   +--------------------+

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
