# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  nixpkgs.hostPlatform = "x86_64-linux";

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # LUKS encrypted root partition with TPM2 auto-unlock
  boot.initrd.systemd.enable = true;
  boot.initrd.luks.devices."luks-fa89f27a-14c6-42eb-97a0-9e57f465d583" = {
    device = "/dev/disk/by-uuid/fa89f27a-14c6-42eb-97a0-9e57f465d583";
    cryptTabExtraOpts = [ "tpm2-device=auto" ];
  };

  fileSystems."/" =
    { device = "/dev/mapper/luks-fa89f27a-14c6-42eb-97a0-9e57f465d583";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4E67-533A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
  hardware.cpu.amd.updateMicrocode = true;
}
